- name: mkdir .local/bin
  file:
    path: "{{ home }}/.local/bin"
    state: directory
    mode: 0755
- name: Install tools
  include_tasks: "{{ ansible_distribution }}.yaml"

- name: install asdf
  vars:
    asdf_init_shell: true
    asdf_plugins:
      - name: nodejs
  include_role:
    name: markosamuli.asdf

- name: update asdf
  become: false
  shell: /bin/bash -c '. ${ASDF_DATA_DIR:=$HOME/.asdf}/asdf.sh && asdf update'

- name: import OpenPGP keys
  shell: bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'
  changed_when: false

- name: install asdf plugins
  vars:
    asdf_init_shell: false
  include_role:
    name: markosamuli.asdf

- name: global latest asdf
  shell: /bin/bash -c '. ${ASDF_DATA_DIR:=$HOME/.asdf}/asdf.sh && asdf global {{ item.name }} $(asdf latest {{ item.name }})'
  loop: "{{ asdf_plugins }}"

- name: Install npm packages
  shell: /bin/bash -c '. ${ASDF_DATA_DIR:=$HOME/.asdf}/asdf.sh && npm i -g {{ item }}'
  loop: "{{ npm.install_apps }}"

- name: Install rustup stable
  become: false
  shell: /bin/bash -c '. ${ASDF_DATA_DIR:=$HOME/.asdf}/asdf.sh && rustup install stable'

- name: Install rustup default stable
  become: false
  shell: /bin/bash -c '. ${ASDF_DATA_DIR:=$HOME/.asdf}/asdf.sh && rustup default stable'

- name: Install latest rustup
  become: false
  shell: /bin/bash -c '. ${ASDF_DATA_DIR:=$HOME/.asdf}/asdf.sh && rustup update'
- name: Install cargo tools
  become: false
  shell: /bin/bash -c '. ${ASDF_DATA_DIR:=$HOME/.asdf}/asdf.sh && cargo install {{ item }}'
  loop: "{{ rust.install_crates }}"

- name: Install rustup components
  become: false
  shell: /bin/bash -c '. ${ASDF_DATA_DIR:=$HOME/.asdf}/asdf.sh && rustup component add {{ item }}'
  loop: "{{ rust.install_rustup_components }}"

- name: check rust-analyzer
  stat:
    path: "{{ home }}/.local/bin/rust-analyzer"
  register: installed_rust_analyzer
  changed_when: false

- name: Create .local/bin dir if nothing.
  file:
    path: "{{ home }}/.local/bin"
    state: "directory"

- name: Install rust-analyzer
  block:
    - name: Download rust-analyzer
      get_url: url=https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-linux dest={{ home }}/.local/bin/rust-analyzer
    - name: Install rust-analyzer
      become: false
      shell: chmod +x {{ home }}/.local/bin/rust-analyzer
  when: not installed_rust_analyzer.stat.exists

- name: Install oh-my-bash
  git:
    repo: "https://github.com/ohmybash/oh-my-bash.git"
    dest: "{{ home }}/.oh-my-bash"

- name: check NERD fonts
  stat:
    path: "{{ home }}/dotfiles/ansible/nerd-fonts"
  register: has_nerd_fonts

- name: clone nerd-fonts
  shell: git clone https://github.com/ryanoasis/nerd-fonts.git
  when: not has_nerd_fonts.stat.exists

- name: install nerd-fonts
  shell: nerd-fonts/install.sh
  when: not has_nerd_fonts.stat.exists
