- name: update apt cache
  become: true
  apt:
    update_cache: true

- name: for add repository
  become: true
  apt:
    name: "{{ item }}"
  loop:
    - apt-transport-https
    - ca-certificates
    - gnupg-agent
    - software-properties-common

- name: add apt keys
  become: true
  apt_key:
    url: "{{ item }}"
    state: present
  loop: "{{ apt.add_keys }}"

- name: add apt repositories
  become: true
  apt_repository:
    update_cache: true
    repo: "{{ item }}"
    state: present
  loop: "{{ apt.add_repositories }}"

- name: update apt cache
  become: true
  apt:
    update_cache: true

- name: install apt apps
  become: true
  apt:
    name: "{{ item }}"
  loop: "{{ apt.install_apps }}"

- name: Install pip packages.
  pip:
    name: "{{ item }}"
  loop: "{{ pip.install_apps }}"

- name: add docker group
  become: true
  shell: groupadd docker
  failed_when: false

- name: get the username running the deploy
  become: false
  shell: whoami
  register: username_on_the_host
  changed_when: false

- name: gpasswd docker
  become: true
  shell: "gpasswd -a {{ username_on_the_host.stdout }} docker"
