- name: Set locale
  become: false
  shell: localectl set-locale LANG=ja_JP.UTF-8

- name: set timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo

- name: Change English Dir
  become: false
  ignore_errors: true
  shell: LANG=C xdg-user-dirs-gtk-update
