- name: install language-pack-ja
  become: true
  apt: name={{ item }} update_cache=yes
  loop:
    - language-pack-ja
    - manpages-ja
    - manpages-ja-dev

- name: create locale ja_JP.UTF-8
  become: true
  locale_gen:
    name: ja_JP.UTF-8

- name: Set locale
  become: false
  shell: localectl set-locale LANG=ja_JP.UTF-8 LANGUAGE="ja_JP:ja"

- name: set timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo

- name: Change English Dir
  become: false
  ignore_errors: true
  shell: LANG=C xdg-user-dirs-gtk-update

- name: Change Capslock
  become: true
  shell: gsettings set org.gnome.desktop.input-sources xkb-options "['caps:escape']"
