- name: find home dot settings
  find:
    paths: "{{ dotfiles_dir }}/home/"
    hidden: true
    file_type: "any"
  register: home_list
- name: Create home setting simbolic link
  file:
    src: "{{ item.path }}"
    dest: "{{ home }}/{{ item.path | basename }}"
    state: "link"
    force: true
  with_items: "{{ home_list.files }}"
- name: Create .config dir if nothing.
  file:
    path: "{{ xdg_config_home }}"
    state: "directory"
- name: find .config settings
  find:
    paths: "{{ dotfiles_dir }}/.config/"
    file_type: "any"
  register: config_list
- name: Create .config setting simbolic link
  file:
    src: "{{ item.path }}"
    dest: "{{ xdg_config_home }}/{{ item.path | basename }}"
    state: "link"
    force: true
  with_items: "{{ config_list.files }}"
