apt:
  install_apps:
    - uidmap
    - tar
    - neovim
    - pwgen
    - nodejs
    - npm
    - direnv
    - chromium-browser
    - python3-pip
    - apt-transport-https
    - ca-certificates
    - gnupg-agent
    - software-properties-common
    - tree
    - ffmpeg
    - fzf
    - jq
    - docker-compose
    - xvkbd
    - keepassxc
    - mysql-client
    - libxcb-composite0-dev
    - docker-ce
    - libssl-dev
    - pkg-config
    - gh

  add_keys:
    - https://download.docker.com/linux/ubuntu/gpg
  add_keys_from_keyserver:
    - keyserver: keyserver.ubuntu.com
      id: C99B11DEB97541F0

  add_repositories:
    - "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable"
    - "https://cli.github.com/packages"
pip:
  install_apps:
    - msgpack
    - pynvim

gcloud:
  download_url: "https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ gcloud_sdk_version }}-linux-x86_64.tar.gz?hl=JA"
