- hosts: localhost
  vars:
    xdg_config_home: "$HOME/.config"
    dotfiles_dir: "$HOME/dotfiles"
    home: "$HOME"

  tasks:
    - name: Install ubuntu tools
      include_tasks: tasks/install/ubuntu.yaml
      when:
        - ansible_distribution == "Ubuntu"
    - name: Install general tools
      include_tasks: tasks/install/general.yaml
    - name: Home
      include_tasks: tasks/home.yaml
  roles:
    - role: robertdebock.cargo
      become: true
