- hosts: localhost
  vars:
    xdg_config_home: "$HOME/.config"
    dotfiles_dir: "$HOME/dotfiles"
    home: "$HOME"

  tasks:
    - name: install tools
      include_tasks: tasks/install.yaml
    - name: home
      include_tasks: tasks/home.yaml
  roles:
    - role: robertdebock.cargo
      become: true
