- hosts: localhost
  tasks:
    - name: get Ubuntu version
      shell: lsb_release -cs
      ignore_errors: true
      register: lsb_release
      changed_when: false
    - name: load setting
      include_vars: "vars/install/setting/setting.yaml"
    - name: load setting
      include_vars: "vars/install/setting/{{ ansible_distribution }}.yaml"
    - name: install asdf
      vars:
        asdf_init_shell: true
      include_role:
        name: markosamuli.asdf
    - name: Setting Home
      include_tasks: tasks/home.yaml
    - name: Setting environment
      include_tasks: "tasks/environment/{{ ansible_distribution }}.yaml"
      tags:
        - environment
    - name: Install tools
      include_tasks: tasks/install/install.yaml
