- hosts: localhost
  vars:
    xdg_config_home: "$HOME/.config"
    dotfiles_dir: "$HOME/dotfiles"
    home: "$HOME"

  tasks:
    - name: Setting Home
      include_tasks: tasks/home.yaml
    - name: For Ubuntu
      block:
        - name: Setting environment Ubuntu
          include_tasks: tasks/environment/ubuntu.yaml
        - name: Install Ubuntu tools
          include_tasks: tasks/install/ubuntu.yaml
      when:
        - ansible_distribution == "Ubuntu"
    - name: Install general tools
      include_tasks: tasks/install/general.yaml
  roles:
    - role: robertdebock.cargo
      become: true
