- name: Install npm packages
  become: true
  npm:
    name: "{{ item }}"
    global: true
    state: latest
  with_items:
    - npm
    - n
    - typescript
    - typescript-language-server
    - vscode-html-languageserver-bin
    - vscode-css-languageserver-bin
    - vscode-json-languageserver

- name: Install rustup stable
  become: false
  shell: /bin/bash -lc "source {{ home }}/.profile && rustup install stable"

- name: Install rustup default stable
  become: false
  shell: /bin/bash -lc "source {{ home }}/.profile && rustup default stable"

- name: Install latest rustup
  become: false
  shell: /bin/bash -lc "source {{ home }}/.profile && rustup update"
- name: Install cargo tools
  become: false
  shell: /bin/bash -lc "source {{ home }}/.profile && cargo install {{ crates | join(' ') }}"
  vars:
    crates:
      - wasm-pack
      - wasm-bindgen-cli
      - wasm-snip
      - cargo-generate
      - cargo-atcoder
- name: Install rustup components
  become: false
  shell: /bin/bash -lc "source {{ home }}/.profile && rustup component add {{ components | join(' ') }}"
  vars:
    components:
      - rust-src
      - clippy
- stat:
    path: "{{ home }}/.local/bin/rust-analyzer"
  register: installed_rust_analyzer

- name: Create .local/bin dir if nothing.
  file:
    path: "{{ home }}/.local/bin"
    state: "directory"

- name: Install rust-analyzer
  become: false
  shell: "curl -L https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-linux -o {{ home }}/.local/bin/rust-analyzer && chmod +x {{ home }}/.local/bin/rust-analyzer"
  when: installed_rust_analyzer.stat.exists == false

- name: Install oh-my-bash
  git:
    repo: "https://github.com/ohmybash/oh-my-bash.git"
    dest: "{{ home }}/.oh-my-bash"
