- name: Install npm packages
  become: true
  npm:
    name: "{{ item }}"
    global: true
    state: latest
  with_items:
    - npm
    - n
    - typescript
    - typescript-language-server
- name: Install cargo tools
  become: false
  shell: "cargo install {{ crates | join(' ') }}"
  vars:
    crates:
      - wasm-pack
      - wasm-bindgen-cli
      - wasm-snip
      - cargo-generate
      - cargo-atcoder
