- name: Install npm packages
  become: true
  npm:
    name: "{{ item }}"
    global: true
    state: latest
  with_items:
    - npm
    - n
    - typescript
    - typescript-language-server
    - vscode-html-languageserver-bin
    - vscode-css-languageserver-bin
    - vscode-json-languageserver

- name: Install latest rustup
  become: false
  shell: "rustup update"
- name: Install cargo tools
  become: false
  shell: "cargo install {{ crates | join(' ') }}"
  vars:
    crates:
      - wasm-pack
      - wasm-bindgen-cli
      - wasm-snip
      - cargo-generate
      - cargo-atcoder
- name: Install rustup components
  become: false
  shell: "rustup component add {{ components | join(' ') }}"
  vars:
    components:
      - rust-src
      - clippy
- stat:
    path: "{{ home }}/.local/bin/rust-analyzer"
  register: installed_rust_analyzer

- name: Install rust-analyzer
  become: false
  shell: "curl -L https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-linux -o {{ home }}/.local/bin/rust-analyzer && chmod +x {{ home }}/.local/bin/rust-analyzer"
  when: installed_rust_analyzer.stat.exists == false
