name: install_test
on: [push]
jobs:
  install_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ["ubuntu:latest", "ubuntu:20.04"]
    container:
      image: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: apt install sudo
      - run: ./setup.sh --no-interactive --force-install
        env:
          FORCE_ROOTLESS_INSTALL: 1
