name: install_test
on: [push]
jobs:
  install_test:
    strategy:
      matrix:
        os: [ubuntu:latest, ubuntu:20.04]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: ./setup.sh --no-interactive --force-install
        env:
          FORCE_ROOTLESS_INSTALL: 1
